name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A618C5AEB5FA41F3BFCC2DCF24112B2A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3D594DA99FA747CD8FB2D92551173D09 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8CD4857201D44F3EB985C81696113135 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mayapp'
          slot-name: 'Production'
          package: '.'
